package cse110_group_13.ucsdconnect;

import android.content.Context;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by Jack on 11/7/2016.
 *
 * Class Notes:
 * Based on boilerplate code auto-generated by Android Studio.
 *
 * Description: This class creates the category fragments needed to display the list of
 * categories in the category activity of our app.
 *
 * Public Methods: CategoryFragment()
 *                 newInstance()
 *                 onCreate(Bundle savedInstanceState)
 *                 onCreateView(LayoutInflater inflater, ViewGroup container,
 *                              Bundle savedInstanceState)
 *                 onAttach(Context context)
 *                 onDetach()
 *
 */

public class CategoryFragment extends Fragment {
    private static String ARG_CATEGORIES = "categories";

    private OnCategoryListFragmentInteractionListener mListener;
    private List<Category> mCategory = new ArrayList<Category>();

    public static CategoryFragment categoryFragment = null;

    public CategoryFragment() {
        categoryFragment = this;
    }

    public static CategoryFragment newInstance() {
        CategoryFragment fragment = new CategoryFragment();
        Bundle args = new Bundle();

        List<Category> dummyCategories = new ArrayList<Category>();
        Log.d("CATEGORY_FRAG", "Adding categories to list");

        dummyCategories.add(Category.categoryList.get(0));
        dummyCategories.add(Category.categoryList.get(1));
        dummyCategories.add(Category.categoryList.get(2));
        dummyCategories.add(Category.categoryList.get(3));

        args.putSerializable(ARG_CATEGORIES, (Serializable) dummyCategories);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Bundle args = getArguments();
        if (args != null) {
            mCategory = (List<Category>) args.getSerializable(ARG_CATEGORIES);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_category_list, container, false);

        if (view instanceof RecyclerView) {
            Context context = view.getContext();
            final RecyclerView recyclerView = (RecyclerView) view;
            recyclerView.setLayoutManager(new LinearLayoutManager(context));
            recyclerView.setAdapter(new MyCategoryRecyclerViewAdapter(mCategory, mListener));
        }
        return view;
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnCategoryListFragmentInteractionListener) {
            mListener = (OnCategoryListFragmentInteractionListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnListFragmentInteractionListener");
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    public interface OnCategoryListFragmentInteractionListener {
        void onCategoryInfoRequested(Category category);
    }
}
